# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{habl}
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Florian Aßmann"]
  s.date = %q{2010-04-15}
  s.description = %q{This library simply renders markup haikus to xml
before parsing it with XBEL. See http://github.com/boof/xbel and
http://en.wikipedia.org/wiki/XBEL for more information about XBEL and
http://haml-lang.com/ for Haml.}
  s.email = %q{florian.assmann@email.de}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.md"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "LICENSE",
     "README.md",
     "Rakefile",
     "VERSION",
     "habl.gemspec",
     "lib/habl.rb",
     "test/fixture.xbel.haml",
     "test/habel_test.rb",
     "test/teststrap.rb"
  ]
  s.homepage = %q{http://github.com/boof/habl}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.6}
  s.summary = %q{Shorten your XBEL by writing markup haiku.}
  s.test_files = [
    "test/habel_test.rb",
     "test/teststrap.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<xbel>, [">= 0.2.6"])
      s.add_runtime_dependency(%q<haml>, [">= 2.2.23"])
      s.add_development_dependency(%q<riot>, [">= 0"])
      s.add_development_dependency(%q<yard>, [">= 0"])
    else
      s.add_dependency(%q<xbel>, [">= 0.2.6"])
      s.add_dependency(%q<haml>, [">= 2.2.23"])
      s.add_dependency(%q<riot>, [">= 0"])
      s.add_dependency(%q<yard>, [">= 0"])
    end
  else
    s.add_dependency(%q<xbel>, [">= 0.2.6"])
    s.add_dependency(%q<haml>, [">= 2.2.23"])
    s.add_dependency(%q<riot>, [">= 0"])
    s.add_dependency(%q<yard>, [">= 0"])
  end
end

